### ISSUE TITLE
Error when compile cuda module

### ISSUE THREAD

**Issue by lacie-life** [lyclyc52/NeRF_RPN#9]
Hi, thank you for the great work. I met some errors when compile CUDA module. 
`
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
running install
/home/lacie/miniconda3/envs/nerfrpn/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/home/lacie/miniconda3/envs/nerfrpn/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing sort_vertices.egg-info/PKG-INFO
writing dependency_links to sort_vertices.egg-info/dependency_links.txt
writing top-level names to sort_vertices.egg-info/top_level.txt
reading manifest file 'sort_vertices.egg-info/SOURCES.txt'
writing manifest file 'sort_vertices.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
Traceback (most recent call last):
  File "/home/lacie/Github/NeRF_RPN/nerf_rpn/model/rotated_iou/cuda_op/setup.py", line 4, in <module>
    setup(
  File "/home/lacie/miniconda3/envs/nerfrpn/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/home/lacie/miniconda3/envs/nerfrpn/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/lacie/miniconda3/envs/nerfrpn/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/lacie/miniconda3/envs/nerfrpn/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/lacie/miniconda3/envs/nerfrpn/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/lacie/miniconda3/envs/nerfrpn/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/lacie/miniconda3/envs/nerfrpn/lib/python3.9/site-packages/setuptools/command/install.py", line 80, in run
    self.do_egg_install()
  File "/home/lacie/miniconda3/envs/nerfrpn/lib/python3.9/site-packages/setuptools/command/install.py", line 129, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/lacie/miniconda3/envs/nerfrpn/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/lacie/miniconda3/envs/nerfrpn/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/lacie/miniconda3/envs/nerfrpn/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/lacie/miniconda3/envs/nerfrpn/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/lacie/miniconda3/envs/nerfrpn/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/lacie/miniconda3/envs/nerfrpn/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/lacie/miniconda3/envs/nerfrpn/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/lacie/miniconda3/envs/nerfrpn/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/lacie/miniconda3/envs/nerfrpn/lib/python3.9/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/lacie/miniconda3/envs/nerfrpn/lib/python3.9/site-packages/setuptools/_distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/home/lacie/miniconda3/envs/nerfrpn/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/lacie/miniconda3/envs/nerfrpn/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/lacie/miniconda3/envs/nerfrpn/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/lacie/miniconda3/envs/nerfrpn/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/home/lacie/miniconda3/envs/nerfrpn/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/home/lacie/miniconda3/envs/nerfrpn/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 424, in build_extensions
    self._check_cuda_version(compiler_name, compiler_version)
  File "/home/lacie/miniconda3/envs/nerfrpn/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 798, in _check_cuda_version
    torch_cuda_version = packaging.version.parse(torch.version.cuda)
  File "/home/lacie/miniconda3/envs/nerfrpn/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/version.py", line 52, in parse
    return Version(version)
  File "/home/lacie/miniconda3/envs/nerfrpn/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/version.py", line 196, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
`

Do you have any suggest for me?
 
Thanks!

**Comment by zymk9** [comment]
Seems that no CUDA runtime is found. Maybe you can try `torch.cuda.is_available()` first and see if the correct version of pytorch and cudatoolkit are installed.

**Comment by lacie-life** [comment]
Thanks for your reply. Something is wrong with my CUDA runtime env in WSL2, I change it to Ubuntu, and it works fine.
